# Generated by Django 5.2.6 on 2025-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('balls', 'Balls'), ('training', 'Training Equipment'), ('accessories', 'Accessories'), ('lifestyle', 'Lifestyle')], default='shoes', max_length=50),
        ),
    ]
